# Generated by Django 4.1.2 on 2022-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='DeviceName', max_length=50),
            preserve_default=False,
        ),
    ]
