# Generated by Django 4.1.2 on 2022-11-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='consumption',
            field=models.FloatField(),
        ),
    ]
